import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "ModGen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased bg-gray-100`}>
        <Header />

        <div className="flex min-h-screen relative">
          <div className="w-full absolute top-0 left-0 h-[200px] bg-black z-10"></div>
          <div
            style={{ borderTopRightRadius: "60px" }}
            className="flex-1 p-4 bg-gray-100 overflow-y-auto scrollbar-hide z-20"
          >
            {children}
          </div>

          <Toaster position="top-center" />
        </div>
      </body>
    </html>
  );
}
